# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Github\PyQT5\Practice\SOAP_Command_Tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(703, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("NETGEAR_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.IPAddress_label = QtWidgets.QLabel(Form)
        self.IPAddress_label.setGeometry(QtCore.QRect(20, 20, 71, 31))
        self.IPAddress_label.setObjectName("IPAddress_label")
        self.Port_label = QtWidgets.QLabel(Form)
        self.Port_label.setGeometry(QtCore.QRect(20, 50, 71, 31))
        self.Port_label.setObjectName("Port_label")
        self.APIGroup_label = QtWidgets.QLabel(Form)
        self.APIGroup_label.setGeometry(QtCore.QRect(20, 140, 71, 31))
        self.APIGroup_label.setObjectName("APIGroup_label")
        self.APIName_label = QtWidgets.QLabel(Form)
        self.APIName_label.setGeometry(QtCore.QRect(20, 170, 71, 31))
        self.APIName_label.setObjectName("APIName_label")
        self.IPAddress = QtWidgets.QLineEdit(Form)
        self.IPAddress.setGeometry(QtCore.QRect(80, 30, 81, 16))
        self.IPAddress.setObjectName("IPAddress")
        self.Port = QtWidgets.QLineEdit(Form)
        self.Port.setGeometry(QtCore.QRect(80, 60, 81, 16))
        self.Port.setObjectName("Port")
        self.APIGroup = QtWidgets.QLineEdit(Form)
        self.APIGroup.setGeometry(QtCore.QRect(80, 150, 81, 16))
        self.APIGroup.setObjectName("APIGroup")
        self.APIName = QtWidgets.QLineEdit(Form)
        self.APIName.setGeometry(QtCore.QRect(80, 180, 81, 16))
        self.APIName.setObjectName("APIName")
        self.InputBody_label = QtWidgets.QLabel(Form)
        self.InputBody_label.setGeometry(QtCore.QRect(20, 200, 81, 21))
        self.InputBody_label.setObjectName("InputBody_label")
        self.ExecutionLogs_label = QtWidgets.QLabel(Form)
        self.ExecutionLogs_label.setGeometry(QtCore.QRect(180, -10, 171, 51))
        self.ExecutionLogs_label.setObjectName("ExecutionLogs_label")
        self.SendAPI = QtWidgets.QPushButton(Form)
        self.SendAPI.setGeometry(QtCore.QRect(20, 400, 141, 31))
        self.SendAPI.setObjectName("SendAPI")
        self.Quit = QtWidgets.QPushButton(Form)
        self.Quit.setGeometry(QtCore.QRect(70, 540, 91, 51))
        self.Quit.setObjectName("Quit")
        self.execution_logs = QtWidgets.QTextEdit(Form)
        self.execution_logs.setGeometry(QtCore.QRect(180, 30, 491, 561))
        self.execution_logs.setObjectName("execution_logs")
        self.InputBody = QtWidgets.QPlainTextEdit(Form)
        self.InputBody.setGeometry(QtCore.QRect(20, 230, 141, 151))
        self.InputBody.setObjectName("InputBody")
        self.APIGroup_label_2 = QtWidgets.QLabel(Form)
        self.APIGroup_label_2.setGeometry(QtCore.QRect(20, 80, 71, 31))
        self.APIGroup_label_2.setObjectName("APIGroup_label_2")
        self.APIGroup_label_3 = QtWidgets.QLabel(Form)
        self.APIGroup_label_3.setGeometry(QtCore.QRect(20, 110, 71, 31))
        self.APIGroup_label_3.setObjectName("APIGroup_label_3")
        self.Account = QtWidgets.QLineEdit(Form)
        self.Account.setGeometry(QtCore.QRect(80, 90, 81, 16))
        self.Account.setObjectName("Account")
        self.Password = QtWidgets.QLineEdit(Form)
        self.Password.setGeometry(QtCore.QRect(80, 120, 81, 16))
        self.Password.setObjectName("Password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SOAP Command Tool v1.0.1"))
        self.IPAddress_label.setText(_translate("Form", "IP Address"))
        self.Port_label.setText(_translate("Form", "Port"))
        self.APIGroup_label.setText(_translate("Form", "API Group"))
        self.APIName_label.setText(_translate("Form", "API Name"))
        self.InputBody_label.setText(_translate("Form", "Input Body"))
        self.ExecutionLogs_label.setText(_translate("Form", "Execution Logs"))
        self.SendAPI.setText(_translate("Form", "Send API"))
        self.Quit.setText(_translate("Form", "Quit"))
        self.APIGroup_label_2.setText(_translate("Form", "Account"))
        self.APIGroup_label_3.setText(_translate("Form", "Password"))
